name: social_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.5
  flutter_svg: ^1.0.0
  lottie: ^1.2.1
  smooth_page_indicator: ^1.0.0+2
  conditional_builder_null_safety: ^0.0.6
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.11
  fluttertoast: ^8.0.8
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0



# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie_animations/
#  fonts:
#    - family: Jannah
#      fonts:
#        - asset: assets/fonts/
